### ISSUE TITLE
Windows: could not find `unix` in `os`

### ISSUE THREAD

**Issue by yumetodo** [TakaakiFuruse/jump-kun#18]
On Windows 10 1809,  could not find `unix` in `os` error and another related error has occurred.

```
  Installing jump-kun v0.2.0 (C:\msys64\home\yumetodo\jump-kun)
    Updating crates.io index
   Compiling darling_core v0.9.0
   Compiling serde_derive v1.0.99
   Compiling tuikit v0.2.9
   Compiling crossbeam-deque v0.7.1
   Compiling timer v0.2.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\yumetodo\.cargo\registry\src\github.com-1ecc6299db9ec823\tuikit-0.2.9\src\input.rs:21:14
   |
21 | use std::os::unix::io::AsRawFd;
   |              ^^^^ could not find `unix` in `os`
```

Tooooooooo long build fail log is below:

https://pastebin.com/estistCA

**Comment by TakaakiFuruse** [comment]
@yumetodo 
Thanks for your report and very sorry for my super late response.

It looks the problem is caused by tuikit and the library does not support windows.
https://github.com/lotabout/tuikit/issues/13

And tuikit is a dependency of skim, jump-kun's user interface.
https://github.com/lotabout/skim/blob/master/Cargo.toml

(I need to mention on readme that jump-kun does not support windows... )

**Comment by MurraySobol** [comment]
I am also running on Windows 11 Professional, Version 22H2 (OS Build 22621.1635).
AFAIK this is the latest software update as of today.
According to TakaakiFuruse:
It looks the problem is caused by tuikit and the library does not support windows.
https://github.com/lotabout/tuikit/issues/13

Any timeline as to when this will be supported on Windows 11.
The solution appears to be straight-forward, O/S's should not be specifically referenced.

**Comment by TakaakiFuruse** [comment]
I don't use windows both on  my home pc and work pc and not planning to get one.
If you want to use my code on windows, your are free to fork or copy my code and create new one.
